---
# Jekyll Configuration
title: Your Name - Portfolio
description: Full Stack Developer | Creative Designer
url: "" # Leave empty for GitHub Pages
baseurl: "" # Leave empty if using username.github.io, otherwise "/repository-name"

# For GitHub Pages
github: [metadata]

# Author/Contact Information
author:
  name: Your Name
  email: your.email@example.com
  phone: "+1 (555) 123-4567"
  location: San Francisco, CA
  degree: B.S. Computer Science
  experience: 5+ Years
  freelance: Available
  bio: A passionate full stack developer with a keen eye for design and a love for creating seamless user experiences.

# Social Media
social:
  github: https://github.com/yourusername
  linkedin: https://linkedin.com/in/yourusername
  twitter: https://twitter.com/yourusername
  email: mailto:your.email@example.com

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:path/

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# GitHub Pages settings
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
