
---
# Jekyll Configuration
title: Your Name - Portfolio
description: Full Stack Developer | Creative Designer
url: "https://yourusername.github.io"
baseurl: ""

# Author/Contact Information
author:
  name: Your Name
  email: your.email@example.com
  phone: "+1 (555) 123-4567"
  location: San Francisco, CA
  degree: B.S. Computer Science
  experience: 5+ Years
  freelance: Available
  bio: A passionate full stack developer with a keen eye for design and a love for creating seamless user experiences.

# Social Media
social:
  github: https://github.com/yourusername
  linkedin: https://linkedin.com/in/yourusername
  twitter: https://twitter.com/yourusername
  email: mailto:your.email@example.com

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:path/

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Sass configuration
sass:
  sass_dir: _sass
  style: compressed

# Exclude files from build
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE

# Default values
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Your Name"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
