---
# Jekyll Configuration
title: Abhi S - Portfolio
description: Identity & Access Management | Zero Trust | Cloud Security | Automation Engineer
url: "https://Abhi-ks-dev.github.io" # Leave empty for GitHub Pages
baseurl: "/AbhishekSharma.github.io" # Leave empty if using username.github.io, otherwise "/repository-name"

# For GitHub Pages
github: [metadata]

# Author/Contact Information
author:
  name: Your Name
  email: abhi.ks@gmail.com
  phone: "+1 (555) 123-4567"
  location: Indianapolis, IN
  degree: B.S. Computer Science
  experience: 15+ Years
  #freelance: Available
  bio: Experienced Identity and Access Management engineer focused on designing secure, scalable, and compliant IAM strategies.

# Social Media
social:
  github: https://github.com/yourusername
  linkedin: https://linkedin.com/in/yourusername
  twitter: https://twitter.com/yourusername
  email: mailto:your.email@example.com

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:path/

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# GitHub Pages settings
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
